set_property IOSTANDARD LVCMOS33 [get_ports servoPWM1]
set_property IOSTANDARD LVCMOS33 [get_ports servoPWM2]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]
set_property PACKAGE_PIN E16 [get_ports servoPWM1]
set_property PACKAGE_PIN F13 [get_ports servoPWM2]
